name: Add Label to External Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label
        uses: peter-evans/add-labels@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "external"
        if: github.event.pull_request.user.login != 'akeneo'
